# BASIC

In [3]:
import numpy as np
import pandas as pd

In [34]:
x1=[4,5,6,9,7,8,6,25]

In [35]:
type(x1)

list

In [36]:
a1=np.array(x1)

In [37]:
type(a1)

numpy.ndarray

In [38]:
x2=[5,6,1,2,3,4,5,9]

In [39]:
a2= np.array([x1,x2])

In [40]:
a2

array([[ 4,  5,  6,  9,  7,  8,  6, 25],
       [ 5,  6,  1,  2,  3,  4,  5,  9]])

In [41]:
x1=list(range(11))

In [42]:
x1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [43]:
a1=np.arange(11) # Creating a nd array
a1
type(a1)

numpy.ndarray

In [44]:
a2=np.arange(3,14) #Array starts from 3 to 13
a2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [45]:
a3=np.arange(1,20,2)
a3

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [46]:
a4=np.arange(24,5,-2)
a4

array([24, 22, 20, 18, 16, 14, 12, 10,  8,  6])

In [47]:
a5=np.arange(50,5,-4)
a5

array([50, 46, 42, 38, 34, 30, 26, 22, 18, 14, 10,  6])

In [48]:
a6=np.arange(5,50,4)
a6

array([ 5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49])

# LINSPACE

In [49]:
x1=np.linspace(10,30,7) #3rd value can't be negative or in decimal
x1

array([10.        , 13.33333333, 16.66666667, 20.        , 23.33333333,
       26.66666667, 30.        ])

In [50]:
x2=np.linspace(10,30,7,endpoint=False) # EEnd point won't take last value
x2

array([10.        , 12.85714286, 15.71428571, 18.57142857, 21.42857143,
       24.28571429, 27.14285714])

# ND ARRAY

In [51]:
a1=np.array([4,5,6,8,7,9,2])

In [52]:
np.append(a1,3) #append 3 at last

array([4, 5, 6, 8, 7, 9, 2, 3])

In [53]:
a1

array([4, 5, 6, 8, 7, 9, 2])

In [54]:
a1=np.append(a1,5) # Saved

In [55]:
a1

array([4, 5, 6, 8, 7, 9, 2, 5])

In [56]:
a2=np.array([10,20,30])

In [57]:
a3=np.concatenate((a1,a2)) #Concat 2 array in third array
a3

array([ 4,  5,  6,  8,  7,  9,  2,  5, 10, 20, 30])

In [58]:
a4=np.insert(a3,3,11)
a4

array([ 4,  5,  6, 11,  8,  7,  9,  2,  5, 10, 20, 30])

In [59]:
np.delete(a4,1)

array([ 4,  6, 11,  8,  7,  9,  2,  5, 10, 20, 30])

In [60]:
a4

array([ 4,  5,  6, 11,  8,  7,  9,  2,  5, 10, 20, 30])

In [61]:
a1=np.array([3,5,6,78,8,2,3,5,6,7])

In [62]:
len(a1)

10

RESHAPE

In [63]:
a2=a1.reshape(5,2) #This will convert 1D arrray into 2D array
a2

array([[ 3,  5],
       [ 6, 78],
       [ 8,  2],
       [ 3,  5],
       [ 6,  7]])

In [64]:
# a3=a1.reshape(4,2) #this wont work because elements are 10 and matrix is (4,2)

ValueError: cannot reshape array of size 10 into shape (4,2)

In [65]:
a3=a1.reshape(2,5)
a3

array([[ 3,  5,  6, 78,  8],
       [ 2,  3,  5,  6,  7]])

In [66]:
a3=a1.reshape(-1,1) # number of rows=n   number of cols=1
a3

array([[ 3],
       [ 5],
       [ 6],
       [78],
       [ 8],
       [ 2],
       [ 3],
       [ 5],
       [ 6],
       [ 7]])

In [67]:
a4=a1.reshape(-1,2) # number of rows=n , number of cols =2
a4

array([[ 3,  5],
       [ 6, 78],
       [ 8,  2],
       [ 3,  5],
       [ 6,  7]])

In [68]:
a5=a1.reshape(1,-1) # number of rows=1 , number of cols =n(Python will decide)
a5

array([[ 3,  5,  6, 78,  8,  2,  3,  5,  6,  7]])

In [69]:
a2

array([[ 3,  5],
       [ 6, 78],
       [ 8,  2],
       [ 3,  5],
       [ 6,  7]])

In [70]:
a2[1]

array([ 6, 78])

In [71]:
a2[2,:]

array([8, 2])

In [72]:
a2[:,0]

array([3, 6, 8, 3, 6])

In [73]:
a2

array([[ 3,  5],
       [ 6, 78],
       [ 8,  2],
       [ 3,  5],
       [ 6,  7]])

In [74]:
newcol=np.array([3,1,5,9,2])  #creating a row(Array)

In [75]:
newcol=newcol.reshape(-1,1) # Converting that into cols
newcol

array([[3],
       [1],
       [5],
       [9],
       [2]])

In [76]:
a4=np.hstack([a2,newcol]) #Adding newcol to a2
a4                        # Hstack is used

array([[ 3,  5,  3],
       [ 6, 78,  1],
       [ 8,  2,  5],
       [ 3,  5,  9],
       [ 6,  7,  2]])

In [77]:
a5=np.array([10,20,30])

In [78]:
a6=np.vstack([a4,a5])
a6

array([[ 3,  5,  3],
       [ 6, 78,  1],
       [ 8,  2,  5],
       [ 3,  5,  9],
       [ 6,  7,  2],
       [10, 20, 30]])

In [79]:
a7=np.insert(a6,2,[11,22,33],axis=0) # adding a row at particular postition
a7         # (existing array,postion ,array that wanted to be insert,axis=1 for cols and axis=0 for rows)

array([[ 3,  5,  3],
       [ 6, 78,  1],
       [11, 22, 33],
       [ 8,  2,  5],
       [ 3,  5,  9],
       [ 6,  7,  2],
       [10, 20, 30]])

In [80]:
a8=np.insert(a7,2,[0,0,0,0,0,0,0],axis=1) # adding a col at particular position
a8        # (existing array,postion ,array that wanted to be insert,axis=1 for cols and axis=0 for rows)

array([[ 3,  5,  0,  3],
       [ 6, 78,  0,  1],
       [11, 22,  0, 33],
       [ 8,  2,  0,  5],
       [ 3,  5,  0,  9],
       [ 6,  7,  0,  2],
       [10, 20,  0, 30]])

In [81]:
np.delete(a8,2,axis=0) # delete the row of particular postiion

array([[ 3,  5,  0,  3],
       [ 6, 78,  0,  1],
       [ 8,  2,  0,  5],
       [ 3,  5,  0,  9],
       [ 6,  7,  0,  2],
       [10, 20,  0, 30]])

In [82]:
np.delete(a8,(1,2),axis=1) #delete the col of particular position

array([[ 3,  3],
       [ 6,  1],
       [11, 33],
       [ 8,  5],
       [ 3,  9],
       [ 6,  2],
       [10, 30]])

# BROADCASTING

In [4]:
a1=np.array([4,5,6,7,8,9])
a2=np.array([10,20,60,50,40,90])

In [5]:
a3=a1+5
a3

array([ 9, 10, 11, 12, 13, 14])

In [6]:
a3=2*a1+5
a3

array([13, 15, 17, 19, 21, 23])

In [7]:
a1+a2 # Size of both the array should be Same

array([14, 25, 66, 57, 48, 99])

In [8]:
a1=np.array([3,6,5,4,7,8,9,5,2,5,6,4]) # 1 D array
len(a1)


12

In [9]:
a2=a1.reshape(3,4) #Converting it into 2D Array

In [10]:
a3=np.array([2,4,6,8])

In [11]:
a2+a3 # 

array([[ 5, 10, 11, 12],
       [ 9, 12, 15, 13],
       [ 4,  9, 12, 12]])

In [12]:
a4=np.array([3,4,5])

In [13]:
a4=a4.reshape(-1,1)

In [14]:
a4


array([[3],
       [4],
       [5]])

In [15]:
a2

array([[3, 6, 5, 4],
       [7, 8, 9, 5],
       [2, 5, 6, 4]])

In [16]:
a2+a4

array([[ 6,  9,  8,  7],
       [11, 12, 13,  9],
       [ 7, 10, 11,  9]])

In [17]:
a1

array([3, 6, 5, 4, 7, 8, 9, 5, 2, 5, 6, 4])

In [18]:
a1[[1,3,7]]

array([6, 4, 5])

In [19]:
a1[2]

np.int64(5)

WHERE 

In [36]:
''' 
q1: where are  the values which are greater than 4
q1[0]
q2: how many value are greater than 4
len(q1[0])
(a1>4).sum()
q3: what are the values which are greater than 4
a1[q1]
'''
a1=np.array([5,6,9,8,7,4,1,2])
#Input to np.where command is the condition that needs to be checked
#output of np.where command are the indicies where that condition found to be true
q1=np.where(a1>4)
q1



(array([0, 1, 2, 3, 4]),)

In [33]:
type(q1)

tuple

In [30]:
len(q1)

1

In [31]:
len(q1[0])

5

In [34]:
q1[0]

array([0, 1, 2, 3, 4])

In [37]:
(a1>4).sum()

np.int64(5)

In [39]:
a1[q1]

array([5, 6, 9, 8, 7])

**2D Array**

In [42]:
x1 = (np.arange(48)).reshape(6,8)   # creates a 2d array of 6 rows and 8 columns
x1

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47]])

In [49]:
x2 = np.resize(x1,(12,4))   #  resizes the array x1 which was having 6 rows and 8 cols to an array with 12 rows and 4 cols
x2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47]])

In [47]:
x3 = np.split(x2,[1,3,5])	# splits the array at the indices mentioned. The resultant arrays 
# are different items in a list. So basically we get list of arrays. By defaults axis=0 so splitting is done horizontally
x3

x4=np.split(x2,[2,6,9])
x4

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]),
 array([[36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]])]

In [114]:
x4 = np.split(x1,[2,3,5], axis=1)    # splitting happens vertically
x4

[array([[ 0,  1],
        [ 8,  9],
        [16, 17],
        [24, 25],
        [32, 33],
        [40, 41]]),
 array([[ 2],
        [10],
        [18],
        [26],
        [34],
        [42]]),
 array([[ 3,  4],
        [11, 12],
        [19, 20],
        [27, 28],
        [35, 36],
        [43, 44]]),
 array([[ 5,  6,  7],
        [13, 14, 15],
        [21, 22, 23],
        [29, 30, 31],
        [37, 38, 39],
        [45, 46, 47]])]

In [57]:
b=np.array([2,4,1,7,6,5,9,8,2,3,1,5])
c = sorted(b)          #sorts the array in increasing order
c = sorted(b)[::-1]    # sorts the array in the decreasing order

np.sort(b)     # also PRINTS the array in the increasing order, original array is unchanged

array([1, 1, 2, 2, 3, 4, 5, 5, 6, 7, 8, 9])

In [67]:
b=b.reshape(3,4)   # reshapes b as a 2d array with 3 rows and 4 columns
 
b

array([[2, 4, 1, 7],
       [6, 5, 9, 8],
       [2, 3, 1, 5]])

In [68]:
np.sort(b,axis=0)   # row wise values will be changed. Column values are only rearranged


array([[2, 3, 1, 5],
       [2, 4, 1, 7],
       [6, 5, 9, 8]])

In [69]:
np.sort(b,axis=1)   # column wise values will be changed. Row values are only rearranged

array([[1, 2, 4, 7],
       [5, 6, 8, 9],
       [1, 2, 3, 5]])

In [73]:
c=np.where(b>=4)
c      #ROWS                        #COLS 

(array([0, 0, 1, 1, 1, 1, 2]), array([1, 3, 0, 1, 2, 3, 3]))

In [74]:
b[c]

array([4, 7, 6, 5, 9, 8, 5])

In [77]:
r=[4,9,8]
r2=r*3
r2

[4, 9, 8, 4, 9, 8, 4, 9, 8]

In [83]:
a1=np.array([2,6,5,4])
a2=np.repeat(a1,3)

a2

array([2, 2, 2, 6, 6, 6, 5, 5, 5, 4, 4, 4])

In [86]:
a2=np.repeat(a1,[2,4,3,2])
a2

array([2, 2, 6, 6, 6, 6, 5, 5, 5, 4, 4])

**SORT AND ARGSORT**

In [87]:
a1=np.array([4,7,6,1,5,9,7,8,2])

In [88]:
np.sort(a1) # returns value from lowest to highest

array([1, 2, 4, 5, 6, 7, 7, 8, 9])

In [89]:
np.argsort(a1) # returns indices of the lowest to highest value

array([3, 8, 0, 4, 2, 1, 6, 7, 5])

In [91]:
a1[np.argsort(a1)] # same as np.sort(a1)

array([1, 2, 4, 5, 6, 7, 7, 8, 9])

**UNIQUE & OCCURANCE**

In [94]:
a1=np.array([6,5,4,8,7,6,2,2,5,7,1,8,1,2,5,6,9,4,7,5,6,2,0,8,8,9,2,5])
len(a1)

28

In [98]:
np.unique(a1) 

array([0, 1, 2, 4, 5, 6, 7, 8, 9])

In [100]:
np.unique(a1, return_counts=True) # Returns value and number of times that value appear

(array([0, 1, 2, 4, 5, 6, 7, 8, 9]), array([1, 2, 5, 2, 5, 4, 3, 4, 2]))

In [103]:
np.unique(a1, return_index=True)   #Reurns value and first time that value occurring for the first time

(array([0, 1, 2, 4, 5, 6, 7, 8, 9]),
 array([22, 10,  6,  2,  1,  0,  4,  3, 16]))

In [109]:
np.where(a1==2)

(array([ 6,  7, 13, 21, 26]),)