In [1]:
import numpy as np
import pandas as pd

In [9]:
 #que 1
a=[10,20,30,40,50]
a1=np.array(a)
a1

array([10, 20, 30, 40, 50])

In [5]:
x=[1,0,2,5,9,8,7,4]
y=np.array(x)

In [8]:
type(x)


list

In [7]:
type(y)

numpy.ndarray

In [13]:
b1=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
b1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [15]:
b2=np.array([[1,2,3],[4,5,6]])
b2

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
b2.shape

(2, 3)

In [18]:
b2.ndim

2

Part2:

In [22]:
a1=np.arange(0,21)
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [24]:
a2=np.arange(5,26)
a2

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25])

In [26]:
a3=np.arange(2,31,2)
a3

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [28]:
a4=np.arange(1,26,2)
a4

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25])

In [30]:
a5=np.arange(50,11,-5)
a5

array([50, 45, 40, 35, 30, 25, 20, 15])

In [36]:
np.arange(100,50,-10)

array([100,  90,  80,  70,  60])

Part3

np.linspace(1,10,5)

In [39]:
np.linspace(50,100,10)

array([ 50.        ,  55.55555556,  61.11111111,  66.66666667,
        72.22222222,  77.77777778,  83.33333333,  88.88888889,
        94.44444444, 100.        ])

In [41]:
np.linspace(0,1,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [46]:
np.linspace(10,290,7,endpoint=False)

array([ 10.,  50.,  90., 130., 170., 210., 250.])

In [47]:
np.arange(10,20,2) # here we manually give the space between the  numbers

array([10, 12, 14, 16, 18])

In [52]:
np.linspace(10,30,9) # here we only provide the number of values we want ,python implicitly give the spaces between them

array([10. , 12.5, 15. , 17.5, 20. , 22.5, 25. , 27.5, 30. ])

Part4

In [54]:
x = np.array([2,4,6,8])
y = np.array([1,3,5,7])

In [55]:
x+y

array([ 3,  7, 11, 15])

In [56]:
y-x

array([-1, -1, -1, -1])

In [57]:
x*y

array([ 2, 12, 30, 56])

In [58]:
x**2

array([ 4, 16, 36, 64])

In [59]:
y**3

array([  1,  27, 125, 343])


Part 5

In [60]:
a1 = np.array([1,2,3,4,5,6])
a2 = np.array([4,5,6,7,8,9])

In [61]:
np.intersect1d(a1,a2)

array([4, 5, 6])

In [62]:
np.union1d(a1,a2)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
np.setdiff1d(a1,a2)

array([1, 2, 3])

In [66]:
np.setdiff1d(a2,a1)

array([7, 8, 9])

In [67]:
np.setxor1d(a1,a2)

array([1, 2, 3, 7, 8, 9])

In [74]:
np.isin(a1,a2)

array([False, False, False,  True,  True,  True])

In [75]:
np.where(np.isin(a1,a2))[0]

array([3, 4, 5])

Dot Product and Cross Product

In [76]:
x1 = np.array([2,3,4])
x2 = np.array([1,5,2])

In [77]:
np.dot(x1,x2)

np.int64(25)

In [78]:
np.cross(x1,x2)

array([-14,   0,   7])

In [84]:
x1 = np.array([2,3,6])
x2 = np.array([8,9,2])

In [85]:
np.dot(x1,x2)

np.int64(55)

In [86]:
np.cross(x1,x2)

array([-48,  44,  -6])

Linear Algebra


In [87]:
from numpy import linalg

In [89]:
A = np.array([
    [1,2,3],
    [0,1,4],
    [5,6,0]
])

In [90]:
np.linalg.det(A)

np.float64(0.9999999999999987)

In [91]:
np.transpose(A)

array([[1, 0, 5],
       [2, 1, 6],
       [3, 4, 0]])

In [92]:
np.linalg.inv(A)

array([[-24.,  18.,   5.],
       [ 20., -15.,  -4.],
       [ -5.,   4.,   1.]])

In [93]:
np.invert(A)

array([[-2, -3, -4],
       [-1, -2, -5],
       [-6, -7, -1]])

In [94]:
np.linalg.eigvals(A)

array([-5.2296696 , -0.02635282,  7.25602242])

In [96]:
np.sum(A,axis=0)

array([6, 9, 7])

In [97]:
np.sum(A,axis=1)

array([ 6,  5, 11])

Random

In [99]:
np.random.randint(1,50,5)

array([26,  5,  8, 42, 41], dtype=int32)

In [104]:
np.random.randint(1,100,(3,3))

array([[97, 40, 41],
       [81, 59, 90],
       [17, 91, 52]], dtype=int32)

In [107]:
np.random.rand(10)

array([0.97224529, 0.56795164, 0.23738148, 0.25716886, 0.9910656 ,
       0.57306763, 0.07034594, 0.40292256, 0.1019207 , 0.4334479 ])

In [109]:
np.random.seed(10)
np.random.randint(1,10,5)

array([5, 1, 2, 1, 2], dtype=int32)

In [111]:
# 5. Shuffle an array
arr = np.array([1,2,3,4,5,6,7,8,9])

np.random.shuffle(arr)
arr

array([6, 2, 8, 3, 7, 9, 4, 5, 1])

In [112]:
x = np.array([10,20,30,40,50,60,70])

y = np.random.choice(x, 3)
y

array([10, 50, 70])

# Mini Challenge

## Challenge 1

Create an array from 1 to 100 and:

Print only even numbers
Print numbers divisible by 5
Find the sum of all numbers
Find the average

In [126]:
a=np.arange(1,101)
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [127]:
a[np.where(a%2==0) ]

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [128]:
a[np.where(a%5==0) ]

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

In [131]:
sum=np.sum(a)
sum

np.int64(5050)

In [133]:
avg=np.average(a)
avg

np.float64(50.5)

## Challenge 2
Create a 5×5 matrix and:

Print diagonal elements
Print row sums
Print column sums
Find maximum and minimum value

In [137]:
a=np.array([[1,2,3,4,5],[9,8,7,4,5],[4,5,6,9,8],[9,6,3,2,5],[1,4,5,6,2]])

In [143]:
a

array([[1, 2, 3, 4, 5],
       [9, 8, 7, 4, 5],
       [4, 5, 6, 9, 8],
       [9, 6, 3, 2, 5],
       [1, 4, 5, 6, 2]])

In [144]:
np.sum(np.diagonal(a))

np.int64(19)

In [145]:
np.sum(a,axis=0)

array([24, 25, 24, 25, 25])

In [146]:
np.sum(a,axis=1)

array([15, 33, 32, 25, 18])

In [147]:
np.max(a)

np.int64(9)

In [148]:
np.min(a)

np.int64(1)

## Challenge 3

Take two arrays and:

Find common elements
Find unique elements
Merge them
Sort the final array

In [150]:
a1 = np.array([1,2,3,4,5,6])
a2 = np.array([4,5,6,7,8,9])

In [151]:
np.intersect1d(a1,a2)

array([4, 5, 6])

In [154]:
np.setxor1d(a1,a2)

array([1, 2, 3, 7, 8, 9])

In [160]:
merged=np.union1d(a1,a2)
merged

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [159]:
np.sort(merged)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])