In [1]:
import numpy as np
import pandas as pd

In [2]:
a=np.array([7,5,3,9])
b=np.array([9,5,1,2])

In [3]:
np.dot(a,b)

np.int64(109)

In [4]:
a1=np.zeros([3,3])
a2=np.ones([3,3])
identity_matrix = np.eye(3)

In [5]:
b1=np.hstack((a1,a2))
b1

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [6]:
b2=np.vstack((a1,a2))
b2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np.sum(b2,axis=0)

array([3., 3., 3.])

In [8]:
a2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.random.seed(10)
x1=np.random.randint(10,50,9).reshape(3,3)
x1

array([[19, 46, 25],
       [10, 38, 35],
       [39, 39, 18]], dtype=int32)

In [10]:
sub=np.mean(x1,axis=0)-x1
sub

array([[  3.66666667,  -5.        ,   1.        ],
       [ 12.66666667,   3.        ,  -9.        ],
       [-16.33333333,   2.        ,   8.        ]])

In [11]:
sub=np.mean(x1,axis=1)-x1
sub

array([[ 11.        , -18.33333333,   7.        ],
       [ 20.        , -10.33333333,  -3.        ],
       [ -9.        , -11.33333333,  14.        ]])

In [12]:
np.random.seed(1)
x1=np.random.randint(10,50,25).reshape(5,5)
x1

array([[47, 22, 18, 19, 21],
       [15, 25, 10, 26, 11],
       [22, 17, 16, 35, 30],
       [47, 28, 30, 21, 38],
       [39, 24, 14, 33, 33]], dtype=int32)

In [13]:
from numpy import linalg

norm=np.linalg.norm(x1,axis=0)
norm

array([81.53526844, 52.51666402, 42.14261501, 61.57921727, 63.20601237])

In [14]:
import numpy as np

# 1. Create a 5x5 array with random float values between 0 and 100
np.random.seed(42)  # Setting seed for reproducible results
random_array = np.random.rand(5, 5) * 100
print("Original 5x5 Random Array:")
print(random_array)
print("-" * 50)

# 2. Find the min and max values for each row (axis=1)
# we use keepdims=True to maintain the (5, 1) shape for broadcasting
row_mins = random_array.min(axis=1, keepdims=True)
row_maxs = random_array.max(axis=1, keepdims=True)

# 3. Apply the Min-Max formula row-wise
normalized_row_wise = (random_array - row_mins) / (row_maxs - row_mins)

print("Row-wise Normalized Array (0 to 1):")
print(normalized_row_wise)

Original 5x5 Random Array:
[[37.45401188 95.07143064 73.19939418 59.86584842 15.60186404]
 [15.59945203  5.80836122 86.61761458 60.11150117 70.80725778]
 [ 2.05844943 96.99098522 83.24426408 21.23391107 18.18249672]
 [18.34045099 30.4242243  52.47564316 43.19450186 29.12291402]
 [61.18528947 13.94938607 29.21446485 36.63618433 45.60699842]]
--------------------------------------------------
Row-wise Normalized Array (0 to 1):
[[0.27497505 1.         0.72477469 0.5569929  0.        ]
 [0.12116299 0.         1.         0.67199161 0.80434967]
 [0.         1.         0.85519484 0.20199041 0.16984743]
 [0.         0.35399752 1.         0.72810637 0.31587527]
 [1.         0.         0.32316686 0.48028717 0.67020233]]


In [15]:
import numpy as np

# 1. Create a 5x5 array with random float values between 0 and 100
np.random.seed(52)  # Setting seed for reproducible results
random_array = np.random.rand(5, 5) * 100
print("Original 5x5 Random Array:")
print(random_array)
print("-" * 50)

# 2. Find the min and max values for each row (axis=1)
# we use keepdims=True to maintain the (5, 1) shape for broadcasting
row_mins = random_array.min(axis=0, keepdims=True)
row_maxs = random_array.max(axis=0, keepdims=True)

# 3. Apply the Min-Max formula row-wise
normalized_row_wise = (random_array - row_mins) / (row_maxs - row_mins)

print("Column-wise Normalized Array (0 to 1):")
print(normalized_row_wise)

Original 5x5 Random Array:
[[82.31103407  2.61179816 21.07706399 61.84217693  9.82844653]
 [62.01313099  5.38902196 96.06540578 98.04293742 52.11276503]
 [63.65533448 76.47569483 76.49552946 41.76855796 76.88053063]
 [42.32017504 92.61035715 68.19264849 36.84555913 85.89098554]
 [38.049568    9.49542639 32.48907136 41.51121861 74.22739489]]
--------------------------------------------------
Column-wise Normalized Array (0 to 1):
[[1.         0.         0.         0.40845897 0.        ]
 [0.54140916 0.03085854 1.         1.         0.55591516]
 [0.57851149 0.8207231  0.73902775 0.0804446  0.88153886]
 [0.09648589 1.         0.62830546 0.         1.        ]
 [0.         0.07648598 0.15218375 0.07623953 0.84665788]]


In [16]:
np.random.seed(10)
a=np.random.rand(3,3,3)
sorta=np.sum(a,axis=1)
sorta
a

array([[[0.77132064, 0.02075195, 0.63364823],
        [0.74880388, 0.49850701, 0.22479665],
        [0.19806286, 0.76053071, 0.16911084]],

       [[0.08833981, 0.68535982, 0.95339335],
        [0.00394827, 0.51219226, 0.81262096],
        [0.61252607, 0.72175532, 0.29187607]],

       [[0.91777412, 0.71457578, 0.54254437],
        [0.14217005, 0.37334076, 0.67413362],
        [0.44183317, 0.43401399, 0.61776698]]])

In [17]:
np.random.seed(15)
a=np.random.rand(5,5)
suma=np.sum(a,axis=0)
suma

array([3.50554181, 1.2889917 , 1.88382793, 1.85189151, 2.04232554])

In [18]:
np.random.seed(20)
a=np.random.rand(5,5)
suma=np.sum(a,axis=1)
suma

array([3.22910232, 2.44075115, 3.39949848, 1.39866297, 3.31812387])

In [19]:
np.random.seed(52)
b=np.random.rand(5,5)
partitioned_array = np.partition(b, 3, axis=1)
second_largest = partitioned_array[:, 3]
second_largest

array([0.61842177, 0.96065406, 0.76495529, 0.85890986, 0.41511219])

In [20]:
np.random.seed(52)
b=np.random.rand(5,5)
partitioned_array = np.partition(b, 3, axis=0)
second_largest = partitioned_array[3,:]
second_largest

array([0.63655334, 0.76475695, 0.76495529, 0.61842177, 0.76880531])

In [21]:
second_largest

array([0.63655334, 0.76475695, 0.76495529, 0.61842177, 0.76880531])